#!/bin/bash

echo -e "\e[1;30m"
echo "Connected to host: $(hostname)"
echo "Script: $0"
echo -e "\e[0m"
echo

SCP_DIR=/dev/shm
PROD_DIR=/prjvl01/amily/Amily_Prod/Configurations
CHECKSUM_FILENAME=thresholds.md5

function fatal_error
{
  msg=$@
  echo -e "\e[1;33m${msg}\e[0m"
  exit 1
}

echo "Committing pickles to Git"

# -- Check the checksum file exists
if [[ ! -f ${SCP_DIR}/${CHECKSUM_FILENAME} ]]
then
  fatal_error "MD5 hash file is missing. Cannot identify which files to commit."
fi

# -- Check each file listed in the checksum file
(cd ${SCP_DIR}; md5sum --check ${CHECKSUM_FILENAME}) || fatal_error "Checksum check failed!"

echo
echo

# -- Move the files to the production directory
echo "Git operations:"

cd ${PROD_DIR}

echo ".. set author"
export GIT_AUTHOR_NAME="Amily Self Service"
export GIT_AUTHOR_EMAIL=""

echo ".. add"
cat ${SCP_DIR}/${CHECKSUM_FILENAME} | while read checksum filename
do
  sudo -i git add $filename || fatal_error "Failed on 'git add'"
done
echo

echo ".. commit"
#sudo -i git commit -m "Commit pickles generated by Self Service" || fatal_error "Failed on 'git commit'"
echo

echo ".. push"
#sudo -i git push


echo ".. All done!"

exit 0
